#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Rate Limiting Implementation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing Python dependencies..."
# Assuming the script is in .auto-claude/specs/002-rate-limiting-implementation/
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../../.." && pwd )"
cd "$PROJECT_ROOT"
poetry install

# ============================================
# START SERVICE
# ============================================

echo ""
echo "Starting FastAPI backend service..."
poetry run uvicorn backend.main:app --reload --port 8500 &
BACKEND_PID=$!
wait_for_service 8500 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:     http://localhost:8500"
echo "  API Docs:        http://localhost:8500/docs"
echo "  Health Check:    http://localhost:8500/api/health"
echo ""
echo "Process IDs:"
echo "  Backend: $BACKEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
