#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for CloudOpsTools Rebranding

set -e

echo "========================================"
echo "Starting Development Environment"
echo "CloudOpsTools Rebranding Spec 001"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
cd /home/todd/git/CloudOpsTools

if ! command -v poetry &> /dev/null; then
    echo -e "${RED}Poetry not found. Please install Poetry first.${NC}"
    exit 1
fi

poetry install

# ============================================
# START MAIN SERVICE
# ============================================

echo ""
echo "Starting main service (FastAPI)..."

# Start the main application in the background
poetry run uvicorn backend.main:app --reload --port 8500 &
BACKEND_PID=$!

# Wait for backend to be ready
wait_for_service 8500 "FastAPI Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main Application: http://localhost:8500"
echo "  API Documentation: http://localhost:8500/docs"
echo "  Health Check: http://localhost:8500/api/health"
echo ""
echo "Service PIDs:"
echo "  Backend: $BACKEND_PID"
echo ""
echo -e "${GREEN}Ready for implementation!${NC}"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
